import '/src/frontend/src/styles.css';
import '/src/frontend/src/mobile/styles.css';
import {createIcons, icons} from 'lucide';
import {renderShell} from '/src/frontend/src/shell.ts';
import {translate} from '/src/frontend/src/i18n.ts';
import {createMobileKeyboardController} from '/src/frontend/src/mobile/keyboard-controller.ts';
import {mobileKeyboardPresetLayout} from '/src/frontend/src/mobile/keyboard-layout.ts';
import {captureMobileInputTarget} from '/src/frontend/src/mobile/input-target.ts';
import {createMobileExperience} from '/src/frontend/src/mobile/experience.ts';
import {createMobileSystemKeyboardController} from '/src/frontend/src/mobile/system-keyboard-controller.ts';
import {createMobileWorkspaceOverviewController} from '/src/frontend/src/mobile/workspace-overview-controller.ts';
import {prepareMobileOverlay} from '/src/frontend/src/mobile/overlay.ts';
for(const side of ['top','right','bottom','left'])document.documentElement.style.setProperty(`--lzc-safe-area-inset-${side}`,'0px');
const tr=(key,values)=>translate('zh-CN',key,values);
const el=renderShell(document.querySelector('#app'));
el.mobileShortcutClock.textContent='17:42';el.mobileShortcutClock.dataset.compact='true';
el.emptyState.hidden=true;el.targetLabel.textContent='移动端测试 · dev';
const terminalInput=document.createElement('textarea');terminalInput.id='qa-terminal-input';terminalInput.setAttribute('aria-label','Test terminal input');terminalInput.style.cssText='position:absolute;left:24px;top:60px;width:calc(100% - 48px);height:100px;background:var(--surface);color:var(--text);border:1px solid var(--line);font:16px var(--font-mono)';el.terminalStage.append(terminalInput);
const pane=(id,backend='webshell')=>({id,sessionId:`session-${id}`,selector:'dev@owner',title:`终端 ${id}`,label:id,sessionBackend:backend,connectionState:'connected',replaying:false,closing:false,exited:false});
window.qa={pane:pane('a'),generation:1,bytes:[],remote:[],fail:false,defer:false,phrases:[{id:'one',label:'查看目录',text:'ls -la',group:'日常',sendEnter:false,lastUsedAt:0,useCount:0,order:0},{id:'two',label:'运行测试',text:'npm test',group:'开发',sendEnter:true,lastUsedAt:100,useCount:1,order:1}],layout:mobileKeyboardPresetLayout('default'),preset:'default',herdr:{selector:'dev@owner',available:true,focused_pane_id:'remote-a',panes:[]},remotePane:'remote-a'};
const qa=window.qa;
const keyboard=createMobileKeyboardController({root:el.mobileShortcuts,preserveSystemKeyboardState:()=>system.preserveState(),onKeyInput:text=>qa.bytes.push(text),onPasteShortcut:async()=>{},onAction:async action=>{qa.actions??=[];qa.actions.push({action,pane:qa.pane.id,time:performance.now()});
 if(action==='compose-text')experience.openComposer();else if(action==='command-palette')experience.openPalette();else if(action==='workspace-overview'){experience.close();overview.open();}else if(action==='toggle-system-keyboard')system.toggle();
},onPhrase:async()=>{}});
const system=createMobileSystemKeyboardController({activePane:()=>qa.pane,dismissPane:()=>terminalInput.blur(),enableAllPanes:()=>{},focusHardwarePane:()=>terminalInput.blur(),focusPane:()=>{terminalInput.focus();return true},isPaneKeyboardFocused:()=>document.activeElement===terminalInput,updateToggle:keyboard.updateSystemKeyboardState});
const items=()=>[{id:'tab-a',label:'开发工作区',detail:'dev@owner',active:qa.pane.id==='a',panes:[{id:'a',label:'终端 a',detail:'WebShell',status:'已连接',backend:'webshell',active:qa.pane.id==='a'}]},{id:'tab-b',label:'后台构建',detail:'dev@owner',active:qa.pane.id==='b',panes:[{id:'b',label:'终端 b',detail:'Herdr',status:'重连中',backend:'herdr',active:qa.pane.id==='b'}]}];
const overview=createMobileWorkspaceOverviewController({root:el.mobileWorkspaceOverview,items,activate:(_,id)=>{qa.switch(id);qa.selected=id},prepare:()=>prepareMobileOverlay(()=>system.dismissForOverlay()),restoreFallback:()=>{},updateIcons:()=>createIcons({icons}),tr});overview.bind();
const remote=async(data)=>{qa.remote.push(data);if(qa.defer)await new Promise(resolve=>qa.finish=resolve);if(qa.fail)throw new Error('模拟发送失败')};
const experience=createMobileExperience({target:()=>captureMobileInputTarget(qa.pane,qa.generation,qa.herdr),phrases:()=>qa.phrases,keys:()=>qa.layout.pages.flatMap(page=>page.keys),phraseUsed:id=>{const p=qa.phrases.find(p=>p.id===id);if(p){p.lastUsedAt=Date.now();p.useCount++}},canWrite:()=>!qa.readonly,sendBytes:(_,text)=>{if(qa.fail)return false;qa.bytes.push(text);return true},nativeKey:(_,text)=>{if(qa.fail)return false;qa.bytes.push(text);return true},ensureHerdr:async()=>qa.pane.selector,currentHerdrPane:async()=>qa.remotePane,sendHerdrInput:async(selector,paneId,text,enter)=>remote({selector,paneId,text,enter}),sendHerdrKeys:async(selector,paneId,keys)=>remote({selector,paneId,keys}),sendHerdrRaw:async(selector,paneId,text)=>remote({selector,paneId,text}),prepare:()=>prepareMobileOverlay(()=>system.dismissForOverlay()),closeNavigation:keyboard.closeNavigationPad,cancelKeys:keyboard.stopRepeatInput,closeOverview:()=>{if(overview.isOpen())overview.close()},tr});
qa.switch=(id,backend='webshell')=>{qa.pane=pane(id,backend);experience.observe(qa.pane,'\x1b[?2004h');experience.sync()};
qa.refresh=()=>{keyboard.renderQuickInput({phrases:qa.phrases,symbolAgent:'default',tr,layout:qa.layout,preset:qa.preset});createIcons({icons})};
qa.experience=experience;qa.keyboard=keyboard;qa.system=system;qa.overview=overview;qa.refresh();keyboard.bind();experience.observe(qa.pane,'\x1b[?2004h');
for(const node of document.querySelectorAll('[data-i18n]'))node.textContent=tr(node.dataset.i18n);
for(const node of document.querySelectorAll('[data-i18n-aria]'))node.setAttribute('aria-label',tr(node.dataset.i18nAria));
document.addEventListener('keydown',event=>{if(experience.ownsEvent(event))return;},true);
qa.point=selector=>{const node=document.querySelector(selector);node.scrollIntoView({block:'nearest',inline:'nearest'});const r=node.getBoundingClientRect();const p={x:r.left+r.width/2,y:r.top+r.height/2};qa.lastPoint={selector,...p,hit:document.elementFromPoint(p.x,p.y)?.outerHTML.slice(0,160)};return p};
qa.ready=true;
